# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57d2c49615874f564bc939c18af9b5e3d02eb2ba9aa5556727cfe45da5a41de9e9867fc4a09e807293e8d470bf39db358e48f91ae23ff4067fdde7ab4035717f

test:
  secret_key_base: ae8f76f64341a30825fa5f5aab89a8ef2052d04f51e1b83d082d474d9373836e8af50bb7ef241f1f0101abbc0a7792a6eecf7e01e2ac4c9aadbb53f53dcc9273

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
